#Words for hangman game

words = (
    "lion", "tiger", "elephant", "giraffe", "zebra", "kangaroo", "koala", "panda",
    "gorilla", "chimpanzee", "orangutan", "gibbon", "baboon", "lemur", "sloth",
    "armadillo", "anteater", "aardvark", "hedgehog", "porcupine", "beaver", "otter",
    "weasel", "ferret", "mink", "badger", "wolverine", "skunk", "raccoon", "opossum",
    "bat", "mouse", "rat", "squirrel", "chipmunk", "gopher", "vole", "shrew", "mole",
    "rabbit", "hare", "deer", "elk", "moose", "caribou", "reindeer", "antelope",
    "gazelle", "impala", "wildebeest", "buffalo", "bison", "yak", "ox", "cow", "bull",
    "horse", "donkey", "mule", "zebu", "camel", "llama", "alpaca", "vicuna", "pig",
    "boar", "warthog", "hippopotamus", "rhinoceros", "tapir", "dolphin", "whale",
    "orca", "narwhal", "seal", "sea lion", "walrus", "manatee", "dugong", "fox",
    "wolf", "coyote", "jackal", "hyena", "cheetah", "leopard", "jaguar", "cougar",
    "lynx", "bobcat", "ocelot", "caracal", "serval", "meerkat", "mongoose", "civet",
    "genet", "bear", "polar bear", "grizzly bear", "black bear", "sun bear",
    "sloth bear", "kinkajou", "coati", "raccoon dog", "dingo", "hyrax", "pangolin",
    "aardwolf", "eagle", "hawk", "falcon", "kestrel", "osprey", "vulture", "condor",
    "owl", "raven", "crow", "magpie", "jay", "sparrow", "finch", "canary", "robin",
    "cardinal", "bluebird", "blackbird", "starling", "swallow", "swift",
    "hummingbird", "woodpecker", "kingfisher", "toucan", "parrot", "macaw",
    "cockatoo", "parakeet", "budgerigar", "pigeon", "dove", "quail", "pheasant",
    "partridge", "grouse", "turkey", "chicken", "rooster", "duck", "goose", "swan",
    "flamingo", "heron", "crane", "stork", "ibis", "pelican", "albatross", "seagull",
    "tern", "puffin", "penguin", "ostrich", "emu", "cassowary", "kiwi bird",
    "peacock", "cuckoo", "nightingale", "lark", "wren", "chickadee", "nuthatch",
    "thrush", "warbler", "oriole", "tanager", "waxwing", "kite", "harrier",
    "buzzard", "crocodile", "alligator", "caiman", "gharial", "turtle", "tortoise",
    "terrapin", "snake", "python", "cobra", "viper", "rattlesnake", "anaconda",
    "boa", "mamba", "adder", "gecko", "iguana", "chameleon", "komodo dragon",
    "monitor lizard", "skink", "gila monster", "frog", "toad", "salamander",
    "newt", "axolotl", "shark", "hammerhead", "tuna", "salmon", "trout", "bass",
    "catfish", "carp", "cod", "herring", "mackerel", "sardine", "anchovy", "eel",
    "moray eel", "swordfish", "marlin", "barracuda", "piranha", "guppy",
    "goldfish", "koi", "angelfish", "clownfish", "pufferfish", "seahorse",
    "stingray", "manta ray", "octopus", "squid", "cuttlefish", "nautilus",
    "jellyfish", "starfish", "sea urchin", "sea cucumber", "crab", "lobster",
    "shrimp", "prawn", "krill", "barnacle", "clam", "oyster", "mussel", "scallop",
    "snail", "slug", "ant", "bee", "wasp", "hornet", "butterfly", "moth",
    "dragonfly", "damselfly", "grasshopper", "cricket", "cockroach", "beetle",
    "ladybug", "firefly", "mosquito", "fly", "termite", "praying mantis",
    "stick insect", "cicada", "aphid", "flea", "tick", "spider", "tarantula",
    "scorpion", "centipede", "millipede", "platypus", "echidna", "wombat",
    "quokka", "tasmanian devil", "capybara", "chinchilla", "guinea pig",
    "hamster", "gerbil", "muskrat", "vervet monkey", "macaque", "tamarin",
    "marmoset", "howler monkey", "spider monkey", "colobus monkey", "okapi",
    "springbok", "kudu", "eland", "oryx", "ibex", "chamois", "markhor",
    "mountain goat", "bighorn sheep", "musk ox", "narwal duplicate check",
    "vole mouse duplicate check", "kookaburra", "lyrebird", "bowerbird",
    "hoatzin", "secretary bird", "shoebill", "hornbill", "roadrunner",
    "sandpiper", "plover", "avocet", "curlew","apple", "banana", "orange", "grape", "grapefruit", "lemon", "lime",
    "mandarin", "tangerine", "clementine", "kumquat", "pineapple", "mango",
    "papaya", "guava", "pomegranate", "fig", "date", "kiwi", "dragonfruit",
    "passionfruit", "lychee", "rambutan", "longan", "mangosteen", "durian",
    "jackfruit", "breadfruit", "star fruit", "persimmon", "quince", "apricot",
    "peach", "nectarine", "plum", "cherry", "pear", "watermelon", "cantaloupe",
    "honeydew", "muskmelon", "strawberry", "blueberry", "raspberry",
    "blackberry", "cranberry", "gooseberry", "currant", "elderberry",
    "mulberry", "boysenberry", "blackcurrant", "redcurrant", "huckleberry",
    "cloudberry", "lingonberry", "acai berry", "goji berry", "coconut",
    "avocado", "olive", "tamarind", "custard apple", "soursop", "cherimoya",
    "sapodilla", "jujube", "loquat", "medlar", "pawpaw", "ugli fruit",
    "pomelo", "bergamot", "yuzu", "calamansi", "plantain", "horned melon",
    "prickly pear", "cactus fruit", "feijoa", "ackee", "salak", "mamey",
    "sapote", "canistel", "jaboticaba", "physalis", "ground cherry",
    "cape gooseberry", "damson", "greengage", "mirabelle", "quandong",
    "finger lime", "buddha's hand", "citron", "satsuma", "tangelo",
    "ortanique", "blood orange", "seville orange", "valencia orange",
    "navel orange", "cavendish banana", "red banana", "plantain banana",
    "sugar apple", "wax apple", "rose apple", "elephant apple",
    "monkey fruit", "star apple", "black sapote", "white sapote",
    "miracle fruit", "buddhas melon", "casaba melon", "galia melon",
    "charentais melon", "crenshaw melon", "santa claus melon",
    "korean melon", "winter melon", "bitter melon", "snake melon",
    "horned cucumber", "gooseberry cape", "surinam cherry", "governor's plum",
    "otaheite gooseberry", "indian gooseberry", "amla", "chico fruit",
    "champedak", "durian belanda", "langsat", "duku", "santol", "marang",
    "bignay", "kaffir lime", "makrut lime", "amanatsu", "hyuganatsu",
    "dekopon", "sudachi", "sunki", "buddha hand citron", "tayberry",
    "loganberry", "marionberry", "olallieberry", "salmonberry", "thimbleberry",
    "wineberry", "juneberry", "serviceberry", "chokeberry", "aronia berry",
    "sea buckthorn", "barberry", "sloe berry", "rowan berry", "hawthorn berry",
    "bilberry", "whortleberry", "cowberry", "arctic bramble", "camu camu",
    "pitanga", "jamaican cherry", "peanut butter fruit", "monstera fruit",
    "cempedak", "noni fruit", "kepel fruit", "bael fruit", "wood apple",
    "custard banana", "ice cream bean", "velvet tamarind", "black plum",
    "java plum", "governor plum", "kei apple", "marula fruit", "safou",
    "monkey orange", "wild medlar", "sugar plum", "damson plum",
    "victoria plum", "yellow plum", "chinese plum", "ume plum"
)